# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026, Advanced Micro Devices, Inc.

ROOT := $(src)

ccflags-y += -I$(ROOT)/
# uAPI - use -iquote to prioritize local header over in-tree kernel header
ccflags-y += -iquote$(ROOT)/../../../include/uapi

# All warnings report as errors and keep debug info
ccflags-y += -g -Werror

obj-m += amdrnpu.o

amdrnpu-y := \
	amdrnpu_drv.o   \
	amdrnpu_bank.o  \
	amdrnpu_drm.o   \
	amdrnpu_cmd.o   \
	amdrnpu_rpmsg.o
